// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIn-_HIBMJQxf6n7kZ9IueoYFjb37UTI8',
    appId: '1:515456179461:web:8bb10012f418a6a397ab6c',
    messagingSenderId: '515456179461',
    projectId: 'student-management-syste-a4c5d',
    authDomain: 'student-management-syste-a4c5d.firebaseapp.com',
    storageBucket: 'student-management-syste-a4c5d.appspot.com',
    measurementId: 'G-WLNWHY9ECC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNqRKy3H_4-a7WGuoHNhMtKvre37h8-cg',
    appId: '1:515456179461:android:e7f047faa37b4c9997ab6c',
    messagingSenderId: '515456179461',
    projectId: 'student-management-syste-a4c5d',
    storageBucket: 'student-management-syste-a4c5d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvf-WOz6T-HgeDl27A5spLZvBvjY8cV9w',
    appId: '1:515456179461:ios:63d3d6d9f28ac74497ab6c',
    messagingSenderId: '515456179461',
    projectId: 'student-management-syste-a4c5d',
    storageBucket: 'student-management-syste-a4c5d.appspot.com',
    iosBundleId: 'com.example.admin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvf-WOz6T-HgeDl27A5spLZvBvjY8cV9w',
    appId: '1:515456179461:ios:a814d05daa56460897ab6c',
    messagingSenderId: '515456179461',
    projectId: 'student-management-syste-a4c5d',
    storageBucket: 'student-management-syste-a4c5d.appspot.com',
    iosBundleId: 'com.example.admin.RunnerTests',
  );
}
